#pragma once

#include <string>
#include <unordered_map>
#include <vector>
#include <unordered_set>

/**
 * @brief The KMerifier class is responsible for transforming a set of reads into a set of k-mers.
 *
 * The class takes a set of reads and converts them into a set of k-mers of a specified size. It also provides
 * methods for obtaining the k-mers, k-mers minus one, and unique k-mers minus one.
 */
class KMerifier
{
public:
    /**
     * @brief Default constructor for the KMerifier class.
     */
    KMerifier();

    /**
     * @brief Constructor for the KMerifier class.
     *
     * @param k_mer_size The size of the k-mers to be generated.
     */
    KMerifier(int k_mer_size);

    /**
     * @brief Returns the size of the k-mers generated by the KMerifier object.
     *
     * @return The size of the k-mers generated by the KMerifier object.
     */
    int GetKmerSize() const;

    /**
     * @brief Transforms a set of reads into a set of k-mers.
     *
     * @param reads The set of reads to be transformed into k-mers.
     */
    void TransformReadsToKmers(const std::vector<std::string> &reads);

    /**
     * @brief Returns a map of the k-mers generated by the KMerifier object.
     *
     * @return A map of the k-mers generated by the KMerifier object.
     */
    const std::unordered_map<int, std::string> GetKmers() const;

    /**
     * @brief Returns a map of the k-mers minus one generated by the KMerifier object.
     *
     * @return A map of the k-mers minus one generated by the KMerifier object.
     */
    std::unordered_map<int, std::string> GetKmersMinusOneMers();

    /**
     * @brief Returns a set of unique k-mers minus one generated by the KMerifier object.
     *
     * @return A set of unique k-mers minus one generated by the KMerifier object.
     */
    std::unordered_set<std::string> GetUniqueKMinusOneMers();

private:
    const int k_mer_size_;                          ///< The size of the k-mers to be generated.
    std::unordered_map<int, std::string> kmer_map_; ///< A map of the k-mers generated by the KMerifier object.
};